backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "seiten"
    label: "Seiten"
    files:
      - label: "Projektidee"
        name: "idee"
        file: "content/idee.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }
